<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\css\bootstrap.min.css" />
    <Content Remove="wwwroot\css\demo.css" />
    <Content Remove="wwwroot\css\demo.css.map" />
    <Content Remove="wwwroot\css\fonts.css" />
    <Content Remove="wwwroot\css\fonts.min.css" />
    <Content Remove="wwwroot\css\kaiadmin.css" />
    <Content Remove="wwwroot\css\kaiadmin.css.map" />
    <Content Remove="wwwroot\css\kaiadmin.min.css" />
    <Content Remove="wwwroot\css\plugins.css" />
    <Content Remove="wwwroot\css\plugins.css.map" />
    <Content Remove="wwwroot\css\plugins.min.css" />
    <Content Remove="wwwroot\fonts\fontawesome\fa-brands-400.eot" />
    <Content Remove="wwwroot\fonts\fontawesome\fa-brands-400.svg" />
    <Content Remove="wwwroot\fonts\fontawesome\fa-brands-400.ttf" />
    <Content Remove="wwwroot\fonts\fontawesome\fa-brands-400.woff" />
    <Content Remove="wwwroot\fonts\fontawesome\fa-brands-400.woff2" />
    <Content Remove="wwwroot\fonts\fontawesome\fa-regular-400.eot" />
    <Content Remove="wwwroot\fonts\fontawesome\fa-regular-400.svg" />
    <Content Remove="wwwroot\fonts\fontawesome\fa-regular-400.ttf" />
    <Content Remove="wwwroot\fonts\fontawesome\fa-regular-400.woff" />
    <Content Remove="wwwroot\fonts\fontawesome\fa-regular-400.woff2" />
    <Content Remove="wwwroot\fonts\fontawesome\fa-solid-900.eot" />
    <Content Remove="wwwroot\fonts\fontawesome\fa-solid-900.svg" />
    <Content Remove="wwwroot\fonts\fontawesome\fa-solid-900.ttf" />
    <Content Remove="wwwroot\fonts\fontawesome\fa-solid-900.woff" />
    <Content Remove="wwwroot\fonts\fontawesome\fa-solid-900.woff2" />
    <Content Remove="wwwroot\fonts\simple-line-icons\Simple-Line-Icons.eot" />
    <Content Remove="wwwroot\fonts\simple-line-icons\Simple-Line-Icons.svg" />
    <Content Remove="wwwroot\fonts\simple-line-icons\Simple-Line-Icons.ttf" />
    <Content Remove="wwwroot\fonts\simple-line-icons\Simple-Line-Icons.woff" />
    <Content Remove="wwwroot\fonts\simple-line-icons\Simple-Line-Icons.woff2" />
    <Content Remove="wwwroot\fonts\summernote\summernote.eot" />
    <Content Remove="wwwroot\fonts\summernote\summernote.ttf" />
    <Content Remove="wwwroot\fonts\summernote\summernote.woff" />
    <Content Remove="wwwroot\fonts\summernote\summernote.woff2" />
    <Content Remove="wwwroot\img\arashmil.jpg" />
    <Content Remove="wwwroot\img\bg-404.jpeg" />
    <Content Remove="wwwroot\img\blogpost.jpg" />
    <Content Remove="wwwroot\img\chadengle.jpg" />
    <Content Remove="wwwroot\img\examples\example1-300x300.jpg" />
    <Content Remove="wwwroot\img\examples\example1.jpeg" />
    <Content Remove="wwwroot\img\examples\example10-300x300.jpg" />
    <Content Remove="wwwroot\img\examples\example10.jpeg" />
    <Content Remove="wwwroot\img\examples\example11-300x300.jpg" />
    <Content Remove="wwwroot\img\examples\example11.jpeg" />
    <Content Remove="wwwroot\img\examples\example12-300x300.jpg" />
    <Content Remove="wwwroot\img\examples\example12.jpeg" />
    <Content Remove="wwwroot\img\examples\example2-300x300.jpg" />
    <Content Remove="wwwroot\img\examples\example2.jpeg" />
    <Content Remove="wwwroot\img\examples\example3-300x300.jpg" />
    <Content Remove="wwwroot\img\examples\example3.jpeg" />
    <Content Remove="wwwroot\img\examples\example4-300x300.jpg" />
    <Content Remove="wwwroot\img\examples\example4.jpeg" />
    <Content Remove="wwwroot\img\examples\example5-300x300.jpg" />
    <Content Remove="wwwroot\img\examples\example5.jpeg" />
    <Content Remove="wwwroot\img\examples\example6-300x300.jpg" />
    <Content Remove="wwwroot\img\examples\example6.jpeg" />
    <Content Remove="wwwroot\img\examples\example7-300x300.jpg" />
    <Content Remove="wwwroot\img\examples\example7.jpeg" />
    <Content Remove="wwwroot\img\examples\example8-300x300.jpg" />
    <Content Remove="wwwroot\img\examples\example8.jpeg" />
    <Content Remove="wwwroot\img\examples\example9-300x300.jpg" />
    <Content Remove="wwwroot\img\examples\example9.jpeg" />
    <Content Remove="wwwroot\img\examples\logo.svg" />
    <Content Remove="wwwroot\img\examples\logo1.svg" />
    <Content Remove="wwwroot\img\examples\logo2.svg" />
    <Content Remove="wwwroot\img\examples\logoinvoice.svg" />
    <Content Remove="wwwroot\img\examples\product1.jpg" />
    <Content Remove="wwwroot\img\examples\product10.jpeg" />
    <Content Remove="wwwroot\img\examples\product11.jpeg" />
    <Content Remove="wwwroot\img\examples\product12.jpeg" />
    <Content Remove="wwwroot\img\examples\product2.jpg" />
    <Content Remove="wwwroot\img\examples\product3.jpg" />
    <Content Remove="wwwroot\img\examples\product4.jpg" />
    <Content Remove="wwwroot\img\examples\product5.jpg" />
    <Content Remove="wwwroot\img\examples\product6.jpg" />
    <Content Remove="wwwroot\img\examples\product7.jpg" />
    <Content Remove="wwwroot\img\examples\product8.jpg" />
    <Content Remove="wwwroot\img\flags\ad.png" />
    <Content Remove="wwwroot\img\flags\ae.png" />
    <Content Remove="wwwroot\img\flags\af.png" />
    <Content Remove="wwwroot\img\flags\ag.png" />
    <Content Remove="wwwroot\img\flags\ai.png" />
    <Content Remove="wwwroot\img\flags\al.png" />
    <Content Remove="wwwroot\img\flags\am.png" />
    <Content Remove="wwwroot\img\flags\an.png" />
    <Content Remove="wwwroot\img\flags\ao.png" />
    <Content Remove="wwwroot\img\flags\ar.png" />
    <Content Remove="wwwroot\img\flags\as.png" />
    <Content Remove="wwwroot\img\flags\at.png" />
    <Content Remove="wwwroot\img\flags\au.png" />
    <Content Remove="wwwroot\img\flags\aw.png" />
    <Content Remove="wwwroot\img\flags\ax.png" />
    <Content Remove="wwwroot\img\flags\az.png" />
    <Content Remove="wwwroot\img\flags\ba.png" />
    <Content Remove="wwwroot\img\flags\bb.png" />
    <Content Remove="wwwroot\img\flags\bd.png" />
    <Content Remove="wwwroot\img\flags\be.png" />
    <Content Remove="wwwroot\img\flags\bf.png" />
    <Content Remove="wwwroot\img\flags\bg.png" />
    <Content Remove="wwwroot\img\flags\bh.png" />
    <Content Remove="wwwroot\img\flags\bi.png" />
    <Content Remove="wwwroot\img\flags\bj.png" />
    <Content Remove="wwwroot\img\flags\bm.png" />
    <Content Remove="wwwroot\img\flags\bn.png" />
    <Content Remove="wwwroot\img\flags\bo.png" />
    <Content Remove="wwwroot\img\flags\br.png" />
    <Content Remove="wwwroot\img\flags\bs.png" />
    <Content Remove="wwwroot\img\flags\bt.png" />
    <Content Remove="wwwroot\img\flags\bv.png" />
    <Content Remove="wwwroot\img\flags\bw.png" />
    <Content Remove="wwwroot\img\flags\by.png" />
    <Content Remove="wwwroot\img\flags\bz.png" />
    <Content Remove="wwwroot\img\flags\ca.png" />
    <Content Remove="wwwroot\img\flags\catalonia.png" />
    <Content Remove="wwwroot\img\flags\cc.png" />
    <Content Remove="wwwroot\img\flags\cd.png" />
    <Content Remove="wwwroot\img\flags\cf.png" />
    <Content Remove="wwwroot\img\flags\cg.png" />
    <Content Remove="wwwroot\img\flags\ch.png" />
    <Content Remove="wwwroot\img\flags\ci.png" />
    <Content Remove="wwwroot\img\flags\ck.png" />
    <Content Remove="wwwroot\img\flags\cl.png" />
    <Content Remove="wwwroot\img\flags\cm.png" />
    <Content Remove="wwwroot\img\flags\cn.png" />
    <Content Remove="wwwroot\img\flags\co.png" />
    <Content Remove="wwwroot\img\flags\cr.png" />
    <Content Remove="wwwroot\img\flags\cs.png" />
    <Content Remove="wwwroot\img\flags\cu.png" />
    <Content Remove="wwwroot\img\flags\cv.png" />
    <Content Remove="wwwroot\img\flags\cx.png" />
    <Content Remove="wwwroot\img\flags\cy.png" />
    <Content Remove="wwwroot\img\flags\cz.png" />
    <Content Remove="wwwroot\img\flags\de.png" />
    <Content Remove="wwwroot\img\flags\dj.png" />
    <Content Remove="wwwroot\img\flags\dk.png" />
    <Content Remove="wwwroot\img\flags\dm.png" />
    <Content Remove="wwwroot\img\flags\do.png" />
    <Content Remove="wwwroot\img\flags\dz.png" />
    <Content Remove="wwwroot\img\flags\ec.png" />
    <Content Remove="wwwroot\img\flags\ee.png" />
    <Content Remove="wwwroot\img\flags\eg.png" />
    <Content Remove="wwwroot\img\flags\eh.png" />
    <Content Remove="wwwroot\img\flags\england.png" />
    <Content Remove="wwwroot\img\flags\er.png" />
    <Content Remove="wwwroot\img\flags\es.png" />
    <Content Remove="wwwroot\img\flags\et.png" />
    <Content Remove="wwwroot\img\flags\europeanunion.png" />
    <Content Remove="wwwroot\img\flags\fam.png" />
    <Content Remove="wwwroot\img\flags\fi.png" />
    <Content Remove="wwwroot\img\flags\fj.png" />
    <Content Remove="wwwroot\img\flags\fk.png" />
    <Content Remove="wwwroot\img\flags\fm.png" />
    <Content Remove="wwwroot\img\flags\fo.png" />
    <Content Remove="wwwroot\img\flags\fr.png" />
    <Content Remove="wwwroot\img\flags\ga.png" />
    <Content Remove="wwwroot\img\flags\gb.png" />
    <Content Remove="wwwroot\img\flags\gd.png" />
    <Content Remove="wwwroot\img\flags\ge.png" />
    <Content Remove="wwwroot\img\flags\gf.png" />
    <Content Remove="wwwroot\img\flags\gh.png" />
    <Content Remove="wwwroot\img\flags\gi.png" />
    <Content Remove="wwwroot\img\flags\gl.png" />
    <Content Remove="wwwroot\img\flags\gm.png" />
    <Content Remove="wwwroot\img\flags\gn.png" />
    <Content Remove="wwwroot\img\flags\gp.png" />
    <Content Remove="wwwroot\img\flags\gq.png" />
    <Content Remove="wwwroot\img\flags\gr.png" />
    <Content Remove="wwwroot\img\flags\gs.png" />
    <Content Remove="wwwroot\img\flags\gt.png" />
    <Content Remove="wwwroot\img\flags\gu.png" />
    <Content Remove="wwwroot\img\flags\gw.png" />
    <Content Remove="wwwroot\img\flags\gy.png" />
    <Content Remove="wwwroot\img\flags\hk.png" />
    <Content Remove="wwwroot\img\flags\hm.png" />
    <Content Remove="wwwroot\img\flags\hn.png" />
    <Content Remove="wwwroot\img\flags\hr.png" />
    <Content Remove="wwwroot\img\flags\ht.png" />
    <Content Remove="wwwroot\img\flags\hu.png" />
    <Content Remove="wwwroot\img\flags\id.png" />
    <Content Remove="wwwroot\img\flags\ie.png" />
    <Content Remove="wwwroot\img\flags\il.png" />
    <Content Remove="wwwroot\img\flags\in.png" />
    <Content Remove="wwwroot\img\flags\io.png" />
    <Content Remove="wwwroot\img\flags\iq.png" />
    <Content Remove="wwwroot\img\flags\ir.png" />
    <Content Remove="wwwroot\img\flags\is.png" />
    <Content Remove="wwwroot\img\flags\it.png" />
    <Content Remove="wwwroot\img\flags\jm.png" />
    <Content Remove="wwwroot\img\flags\jo.png" />
    <Content Remove="wwwroot\img\flags\jp.png" />
    <Content Remove="wwwroot\img\flags\ke.png" />
    <Content Remove="wwwroot\img\flags\kg.png" />
    <Content Remove="wwwroot\img\flags\kh.png" />
    <Content Remove="wwwroot\img\flags\ki.png" />
    <Content Remove="wwwroot\img\flags\km.png" />
    <Content Remove="wwwroot\img\flags\kn.png" />
    <Content Remove="wwwroot\img\flags\kp.png" />
    <Content Remove="wwwroot\img\flags\kr.png" />
    <Content Remove="wwwroot\img\flags\kw.png" />
    <Content Remove="wwwroot\img\flags\ky.png" />
    <Content Remove="wwwroot\img\flags\kz.png" />
    <Content Remove="wwwroot\img\flags\la.png" />
    <Content Remove="wwwroot\img\flags\lb.png" />
    <Content Remove="wwwroot\img\flags\lc.png" />
    <Content Remove="wwwroot\img\flags\li.png" />
    <Content Remove="wwwroot\img\flags\lk.png" />
    <Content Remove="wwwroot\img\flags\lr.png" />
    <Content Remove="wwwroot\img\flags\ls.png" />
    <Content Remove="wwwroot\img\flags\lt.png" />
    <Content Remove="wwwroot\img\flags\lu.png" />
    <Content Remove="wwwroot\img\flags\lv.png" />
    <Content Remove="wwwroot\img\flags\ly.png" />
    <Content Remove="wwwroot\img\flags\ma.png" />
    <Content Remove="wwwroot\img\flags\mc.png" />
    <Content Remove="wwwroot\img\flags\md.png" />
    <Content Remove="wwwroot\img\flags\me.png" />
    <Content Remove="wwwroot\img\flags\mg.png" />
    <Content Remove="wwwroot\img\flags\mh.png" />
    <Content Remove="wwwroot\img\flags\mk.png" />
    <Content Remove="wwwroot\img\flags\ml.png" />
    <Content Remove="wwwroot\img\flags\mm.png" />
    <Content Remove="wwwroot\img\flags\mn.png" />
    <Content Remove="wwwroot\img\flags\mo.png" />
    <Content Remove="wwwroot\img\flags\mp.png" />
    <Content Remove="wwwroot\img\flags\mq.png" />
    <Content Remove="wwwroot\img\flags\mr.png" />
    <Content Remove="wwwroot\img\flags\ms.png" />
    <Content Remove="wwwroot\img\flags\mt.png" />
    <Content Remove="wwwroot\img\flags\mu.png" />
    <Content Remove="wwwroot\img\flags\mv.png" />
    <Content Remove="wwwroot\img\flags\mw.png" />
    <Content Remove="wwwroot\img\flags\mx.png" />
    <Content Remove="wwwroot\img\flags\my.png" />
    <Content Remove="wwwroot\img\flags\mz.png" />
    <Content Remove="wwwroot\img\flags\na.png" />
    <Content Remove="wwwroot\img\flags\nc.png" />
    <Content Remove="wwwroot\img\flags\ne.png" />
    <Content Remove="wwwroot\img\flags\nf.png" />
    <Content Remove="wwwroot\img\flags\ng.png" />
    <Content Remove="wwwroot\img\flags\ni.png" />
    <Content Remove="wwwroot\img\flags\nl.png" />
    <Content Remove="wwwroot\img\flags\no.png" />
    <Content Remove="wwwroot\img\flags\np.png" />
    <Content Remove="wwwroot\img\flags\nr.png" />
    <Content Remove="wwwroot\img\flags\nu.png" />
    <Content Remove="wwwroot\img\flags\nz.png" />
    <Content Remove="wwwroot\img\flags\om.png" />
    <Content Remove="wwwroot\img\flags\pa.png" />
    <Content Remove="wwwroot\img\flags\pe.png" />
    <Content Remove="wwwroot\img\flags\pf.png" />
    <Content Remove="wwwroot\img\flags\pg.png" />
    <Content Remove="wwwroot\img\flags\ph.png" />
    <Content Remove="wwwroot\img\flags\pk.png" />
    <Content Remove="wwwroot\img\flags\pl.png" />
    <Content Remove="wwwroot\img\flags\pm.png" />
    <Content Remove="wwwroot\img\flags\pn.png" />
    <Content Remove="wwwroot\img\flags\pr.png" />
    <Content Remove="wwwroot\img\flags\ps.png" />
    <Content Remove="wwwroot\img\flags\pt.png" />
    <Content Remove="wwwroot\img\flags\pw.png" />
    <Content Remove="wwwroot\img\flags\py.png" />
    <Content Remove="wwwroot\img\flags\qa.png" />
    <Content Remove="wwwroot\img\flags\re.png" />
    <Content Remove="wwwroot\img\flags\readme.txt" />
    <Content Remove="wwwroot\img\flags\ro.png" />
    <Content Remove="wwwroot\img\flags\rs.png" />
    <Content Remove="wwwroot\img\flags\ru.png" />
    <Content Remove="wwwroot\img\flags\rw.png" />
    <Content Remove="wwwroot\img\flags\sa.png" />
    <Content Remove="wwwroot\img\flags\sb.png" />
    <Content Remove="wwwroot\img\flags\sc.png" />
    <Content Remove="wwwroot\img\flags\scotland.png" />
    <Content Remove="wwwroot\img\flags\sd.png" />
    <Content Remove="wwwroot\img\flags\se.png" />
    <Content Remove="wwwroot\img\flags\sg.png" />
    <Content Remove="wwwroot\img\flags\sh.png" />
    <Content Remove="wwwroot\img\flags\si.png" />
    <Content Remove="wwwroot\img\flags\sj.png" />
    <Content Remove="wwwroot\img\flags\sk.png" />
    <Content Remove="wwwroot\img\flags\sl.png" />
    <Content Remove="wwwroot\img\flags\sm.png" />
    <Content Remove="wwwroot\img\flags\sn.png" />
    <Content Remove="wwwroot\img\flags\so.png" />
    <Content Remove="wwwroot\img\flags\sr.png" />
    <Content Remove="wwwroot\img\flags\st.png" />
    <Content Remove="wwwroot\img\flags\sv.png" />
    <Content Remove="wwwroot\img\flags\sy.png" />
    <Content Remove="wwwroot\img\flags\sz.png" />
    <Content Remove="wwwroot\img\flags\tc.png" />
    <Content Remove="wwwroot\img\flags\td.png" />
    <Content Remove="wwwroot\img\flags\tf.png" />
    <Content Remove="wwwroot\img\flags\tg.png" />
    <Content Remove="wwwroot\img\flags\th.png" />
    <Content Remove="wwwroot\img\flags\tj.png" />
    <Content Remove="wwwroot\img\flags\tk.png" />
    <Content Remove="wwwroot\img\flags\tl.png" />
    <Content Remove="wwwroot\img\flags\tm.png" />
    <Content Remove="wwwroot\img\flags\tn.png" />
    <Content Remove="wwwroot\img\flags\to.png" />
    <Content Remove="wwwroot\img\flags\tr.png" />
    <Content Remove="wwwroot\img\flags\tt.png" />
    <Content Remove="wwwroot\img\flags\tv.png" />
    <Content Remove="wwwroot\img\flags\tw.png" />
    <Content Remove="wwwroot\img\flags\tz.png" />
    <Content Remove="wwwroot\img\flags\ua.png" />
    <Content Remove="wwwroot\img\flags\ug.png" />
    <Content Remove="wwwroot\img\flags\um.png" />
    <Content Remove="wwwroot\img\flags\us.png" />
    <Content Remove="wwwroot\img\flags\uy.png" />
    <Content Remove="wwwroot\img\flags\uz.png" />
    <Content Remove="wwwroot\img\flags\va.png" />
    <Content Remove="wwwroot\img\flags\vc.png" />
    <Content Remove="wwwroot\img\flags\ve.png" />
    <Content Remove="wwwroot\img\flags\vg.png" />
    <Content Remove="wwwroot\img\flags\vi.png" />
    <Content Remove="wwwroot\img\flags\vn.png" />
    <Content Remove="wwwroot\img\flags\vu.png" />
    <Content Remove="wwwroot\img\flags\wales.png" />
    <Content Remove="wwwroot\img\flags\wf.png" />
    <Content Remove="wwwroot\img\flags\ws.png" />
    <Content Remove="wwwroot\img\flags\ye.png" />
    <Content Remove="wwwroot\img\flags\yt.png" />
    <Content Remove="wwwroot\img\flags\za.png" />
    <Content Remove="wwwroot\img\flags\zm.png" />
    <Content Remove="wwwroot\img\flags\zw.png" />
    <Content Remove="wwwroot\img\img-shadow.png" />
    <Content Remove="wwwroot\img\jm_denis.jpg" />
    <Content Remove="wwwroot\img\kaiadmin\demo1.png" />
    <Content Remove="wwwroot\img\kaiadmin\demo2.png" />
    <Content Remove="wwwroot\img\kaiadmin\demo3.png" />
    <Content Remove="wwwroot\img\kaiadmin\demo4.png" />
    <Content Remove="wwwroot\img\kaiadmin\demo5.png" />
    <Content Remove="wwwroot\img\kaiadmin\demo6.png" />
    <Content Remove="wwwroot\img\kaiadmin\demo7.png" />
    <Content Remove="wwwroot\img\kaiadmin\demo8.png" />
    <Content Remove="wwwroot\img\kaiadmin\demo9.png" />
    <Content Remove="wwwroot\img\kaiadmin\favicon.ico" />
    <Content Remove="wwwroot\img\kaiadmin\favicon.png" />
    <Content Remove="wwwroot\img\kaiadmin\favicon.svg" />
    <Content Remove="wwwroot\img\kaiadmin\icon.png" />
    <Content Remove="wwwroot\img\kaiadmin\icon.svg" />
    <Content Remove="wwwroot\img\kaiadmin\logo_dark.png" />
    <Content Remove="wwwroot\img\kaiadmin\logo_dark.svg" />
    <Content Remove="wwwroot\img\kaiadmin\logo_documentation.png" />
    <Content Remove="wwwroot\img\kaiadmin\logo_light.png" />
    <Content Remove="wwwroot\img\kaiadmin\logo_light.svg" />
    <Content Remove="wwwroot\img\logoproduct.svg" />
    <Content Remove="wwwroot\img\logoproduct2.svg" />
    <Content Remove="wwwroot\img\logoproduct3.svg" />
    <Content Remove="wwwroot\img\mlane.jpg" />
    <Content Remove="wwwroot\img\profile.jpg" />
    <Content Remove="wwwroot\img\profile2.jpg" />
    <Content Remove="wwwroot\img\sauro.jpg" />
    <Content Remove="wwwroot\img\talha.jpg" />
    <Content Remove="wwwroot\img\undraw\undraw_blank_canvas_3rbb.svg" />
    <Content Remove="wwwroot\img\undraw\undraw_creative_team_r90h.svg" />
    <Content Remove="wwwroot\img\undraw\undraw_empty_xct9.svg" />
    <Content Remove="wwwroot\img\undraw\undraw_Hello_qnas.svg" />
    <Content Remove="wwwroot\img\undraw\undraw_not_found_60pq.svg" />
    <Content Remove="wwwroot\img\undraw\undraw_no_data_qbuo.svg" />
    <Content Remove="wwwroot\img\undraw\undraw_page_not_found_su7k.svg" />
    <Content Remove="wwwroot\img\undraw\undraw_sign_in_e6hj.svg" />
    <Content Remove="wwwroot\img\undraw\undraw_tabs_jf82.svg" />
    <Content Remove="wwwroot\img\undraw\undraw_Taken_if77.svg" />
    <Content Remove="wwwroot\img\undraw\undraw_update_uxn2.svg" />
    <Content Remove="wwwroot\img\undraw\undraw_upgrade_06a0.svg" />
    <Content Remove="wwwroot\img\visa.svg" />
    <Content Remove="wwwroot\js\core\bootstrap.min.js" />
    <Content Remove="wwwroot\js\core\jquery-3.7.1.min.js" />
    <Content Remove="wwwroot\js\core\popper.min.js" />
    <Content Remove="wwwroot\js\demo.js" />
    <Content Remove="wwwroot\js\kaiadmin.js" />
    <Content Remove="wwwroot\js\plugin\bootstrap-notify\bootstrap-notify.min.js" />
    <Content Remove="wwwroot\js\plugin\bootstrap-tagsinput\bootstrap-tagsinput.min.js" />
    <Content Remove="wwwroot\js\plugin\bootstrap-toggle\bootstrap-toggle.min.js" />
    <Content Remove="wwwroot\js\plugin\chart-circle\circles.min.js" />
    <Content Remove="wwwroot\js\plugin\chart.js\chart.min.js" />
    <Content Remove="wwwroot\js\plugin\datatables\datatables.min.js" />
    <Content Remove="wwwroot\js\plugin\datepicker\bootstrap-datetimepicker.min.js" />
    <Content Remove="wwwroot\js\plugin\dropzone\dropzone.min.js" />
    <Content Remove="wwwroot\js\plugin\fullcalendar\fullcalendar.min.js" />
    <Content Remove="wwwroot\js\plugin\gmaps\gmaps.js" />
    <Content Remove="wwwroot\js\plugin\jquery-scrollbar\jquery.scrollbar.min.js" />
    <Content Remove="wwwroot\js\plugin\jquery.magnific-popup\jquery.magnific-popup.min.js" />
    <Content Remove="wwwroot\js\plugin\jquery.sparkline\jquery.sparkline.min.js" />
    <Content Remove="wwwroot\js\plugin\jquery.validate\jquery.validate.min.js" />
    <Content Remove="wwwroot\js\plugin\jsvectormap\jsvectormap.min.js" />
    <Content Remove="wwwroot\js\plugin\jsvectormap\world.js" />
    <Content Remove="wwwroot\js\plugin\list.js\list.min.js" />
    <Content Remove="wwwroot\js\plugin\moment\moment.min.js" />
    <Content Remove="wwwroot\js\plugin\owl-carousel\ajax-loader.gif" />
    <Content Remove="wwwroot\js\plugin\owl-carousel\owl.carousel.min.js" />
    <Content Remove="wwwroot\js\plugin\owl-carousel\owl.video.play.png" />
    <Content Remove="wwwroot\js\plugin\select2\select2.full.min.js" />
    <Content Remove="wwwroot\js\plugin\sortable\sortable.min.js" />
    <Content Remove="wwwroot\js\plugin\sticky-sidebar\sticky-sidebar.min.js" />
    <Content Remove="wwwroot\js\plugin\summernote\summernote-lite.min.js" />
    <Content Remove="wwwroot\js\plugin\sweetalert\sweetalert.min.js" />
    <Content Remove="wwwroot\js\plugin\webfont\webfont.min.js" />
    <Content Remove="wwwroot\js\setting-demo.js" />
    <Content Remove="wwwroot\js\setting-demo2.js" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\css\bootstrap.min.css" />
    <None Include="wwwroot\css\demo.css" />
    <None Include="wwwroot\css\demo.css.map" />
    <None Include="wwwroot\css\fonts.css" />
    <None Include="wwwroot\css\fonts.min.css" />
    <None Include="wwwroot\css\kaiadmin.css" />
    <None Include="wwwroot\css\kaiadmin.css.map" />
    <None Include="wwwroot\css\kaiadmin.min.css" />
    <None Include="wwwroot\css\plugins.css" />
    <None Include="wwwroot\css\plugins.css.map" />
    <None Include="wwwroot\css\plugins.min.css" />
    <None Include="wwwroot\fonts\fontawesome\fa-brands-400.eot" />
    <None Include="wwwroot\fonts\fontawesome\fa-brands-400.svg" />
    <None Include="wwwroot\fonts\fontawesome\fa-brands-400.ttf" />
    <None Include="wwwroot\fonts\fontawesome\fa-brands-400.woff" />
    <None Include="wwwroot\fonts\fontawesome\fa-brands-400.woff2" />
    <None Include="wwwroot\fonts\fontawesome\fa-regular-400.eot" />
    <None Include="wwwroot\fonts\fontawesome\fa-regular-400.svg" />
    <None Include="wwwroot\fonts\fontawesome\fa-regular-400.ttf" />
    <None Include="wwwroot\fonts\fontawesome\fa-regular-400.woff" />
    <None Include="wwwroot\fonts\fontawesome\fa-regular-400.woff2" />
    <None Include="wwwroot\fonts\fontawesome\fa-solid-900.eot" />
    <None Include="wwwroot\fonts\fontawesome\fa-solid-900.svg" />
    <None Include="wwwroot\fonts\fontawesome\fa-solid-900.ttf" />
    <None Include="wwwroot\fonts\fontawesome\fa-solid-900.woff" />
    <None Include="wwwroot\fonts\fontawesome\fa-solid-900.woff2" />
    <None Include="wwwroot\fonts\simple-line-icons\Simple-Line-Icons.eot" />
    <None Include="wwwroot\fonts\simple-line-icons\Simple-Line-Icons.svg" />
    <None Include="wwwroot\fonts\simple-line-icons\Simple-Line-Icons.ttf" />
    <None Include="wwwroot\fonts\simple-line-icons\Simple-Line-Icons.woff" />
    <None Include="wwwroot\fonts\simple-line-icons\Simple-Line-Icons.woff2" />
    <None Include="wwwroot\fonts\summernote\summernote.eot" />
    <None Include="wwwroot\fonts\summernote\summernote.ttf" />
    <None Include="wwwroot\fonts\summernote\summernote.woff" />
    <None Include="wwwroot\fonts\summernote\summernote.woff2" />
    <None Include="wwwroot\img\arashmil.jpg" />
    <None Include="wwwroot\img\bg-404.jpeg" />
    <None Include="wwwroot\img\blogpost.jpg" />
    <None Include="wwwroot\img\chadengle.jpg" />
    <None Include="wwwroot\img\examples\example1-300x300.jpg" />
    <None Include="wwwroot\img\examples\example1.jpeg" />
    <None Include="wwwroot\img\examples\example10-300x300.jpg" />
    <None Include="wwwroot\img\examples\example10.jpeg" />
    <None Include="wwwroot\img\examples\example11-300x300.jpg" />
    <None Include="wwwroot\img\examples\example11.jpeg" />
    <None Include="wwwroot\img\examples\example12-300x300.jpg" />
    <None Include="wwwroot\img\examples\example12.jpeg" />
    <None Include="wwwroot\img\examples\example2-300x300.jpg" />
    <None Include="wwwroot\img\examples\example2.jpeg" />
    <None Include="wwwroot\img\examples\example3-300x300.jpg" />
    <None Include="wwwroot\img\examples\example3.jpeg" />
    <None Include="wwwroot\img\examples\example4-300x300.jpg" />
    <None Include="wwwroot\img\examples\example4.jpeg" />
    <None Include="wwwroot\img\examples\example5-300x300.jpg" />
    <None Include="wwwroot\img\examples\example5.jpeg" />
    <None Include="wwwroot\img\examples\example6-300x300.jpg" />
    <None Include="wwwroot\img\examples\example6.jpeg" />
    <None Include="wwwroot\img\examples\example7-300x300.jpg" />
    <None Include="wwwroot\img\examples\example7.jpeg" />
    <None Include="wwwroot\img\examples\example8-300x300.jpg" />
    <None Include="wwwroot\img\examples\example8.jpeg" />
    <None Include="wwwroot\img\examples\example9-300x300.jpg" />
    <None Include="wwwroot\img\examples\example9.jpeg" />
    <None Include="wwwroot\img\examples\logo.svg" />
    <None Include="wwwroot\img\examples\logo1.svg" />
    <None Include="wwwroot\img\examples\logo2.svg" />
    <None Include="wwwroot\img\examples\logoinvoice.svg" />
    <None Include="wwwroot\img\examples\product1.jpg" />
    <None Include="wwwroot\img\examples\product10.jpeg" />
    <None Include="wwwroot\img\examples\product11.jpeg" />
    <None Include="wwwroot\img\examples\product12.jpeg" />
    <None Include="wwwroot\img\examples\product2.jpg" />
    <None Include="wwwroot\img\examples\product3.jpg" />
    <None Include="wwwroot\img\examples\product4.jpg" />
    <None Include="wwwroot\img\examples\product5.jpg" />
    <None Include="wwwroot\img\examples\product6.jpg" />
    <None Include="wwwroot\img\examples\product7.jpg" />
    <None Include="wwwroot\img\examples\product8.jpg" />
    <None Include="wwwroot\img\flags\ad.png" />
    <None Include="wwwroot\img\flags\ae.png" />
    <None Include="wwwroot\img\flags\af.png" />
    <None Include="wwwroot\img\flags\ag.png" />
    <None Include="wwwroot\img\flags\ai.png" />
    <None Include="wwwroot\img\flags\al.png" />
    <None Include="wwwroot\img\flags\am.png" />
    <None Include="wwwroot\img\flags\an.png" />
    <None Include="wwwroot\img\flags\ao.png" />
    <None Include="wwwroot\img\flags\ar.png" />
    <None Include="wwwroot\img\flags\as.png" />
    <None Include="wwwroot\img\flags\at.png" />
    <None Include="wwwroot\img\flags\au.png" />
    <None Include="wwwroot\img\flags\aw.png" />
    <None Include="wwwroot\img\flags\ax.png" />
    <None Include="wwwroot\img\flags\az.png" />
    <None Include="wwwroot\img\flags\ba.png" />
    <None Include="wwwroot\img\flags\bb.png" />
    <None Include="wwwroot\img\flags\bd.png" />
    <None Include="wwwroot\img\flags\be.png" />
    <None Include="wwwroot\img\flags\bf.png" />
    <None Include="wwwroot\img\flags\bg.png" />
    <None Include="wwwroot\img\flags\bh.png" />
    <None Include="wwwroot\img\flags\bi.png" />
    <None Include="wwwroot\img\flags\bj.png" />
    <None Include="wwwroot\img\flags\bm.png" />
    <None Include="wwwroot\img\flags\bn.png" />
    <None Include="wwwroot\img\flags\bo.png" />
    <None Include="wwwroot\img\flags\br.png" />
    <None Include="wwwroot\img\flags\bs.png" />
    <None Include="wwwroot\img\flags\bt.png" />
    <None Include="wwwroot\img\flags\bv.png" />
    <None Include="wwwroot\img\flags\bw.png" />
    <None Include="wwwroot\img\flags\by.png" />
    <None Include="wwwroot\img\flags\bz.png" />
    <None Include="wwwroot\img\flags\ca.png" />
    <None Include="wwwroot\img\flags\catalonia.png" />
    <None Include="wwwroot\img\flags\cc.png" />
    <None Include="wwwroot\img\flags\cd.png" />
    <None Include="wwwroot\img\flags\cf.png" />
    <None Include="wwwroot\img\flags\cg.png" />
    <None Include="wwwroot\img\flags\ch.png" />
    <None Include="wwwroot\img\flags\ci.png" />
    <None Include="wwwroot\img\flags\ck.png" />
    <None Include="wwwroot\img\flags\cl.png" />
    <None Include="wwwroot\img\flags\cm.png" />
    <None Include="wwwroot\img\flags\cn.png" />
    <None Include="wwwroot\img\flags\co.png" />
    <None Include="wwwroot\img\flags\cr.png" />
    <None Include="wwwroot\img\flags\cs.png" />
    <None Include="wwwroot\img\flags\cu.png" />
    <None Include="wwwroot\img\flags\cv.png" />
    <None Include="wwwroot\img\flags\cx.png" />
    <None Include="wwwroot\img\flags\cy.png" />
    <None Include="wwwroot\img\flags\cz.png" />
    <None Include="wwwroot\img\flags\de.png" />
    <None Include="wwwroot\img\flags\dj.png" />
    <None Include="wwwroot\img\flags\dk.png" />
    <None Include="wwwroot\img\flags\dm.png" />
    <None Include="wwwroot\img\flags\do.png" />
    <None Include="wwwroot\img\flags\dz.png" />
    <None Include="wwwroot\img\flags\ec.png" />
    <None Include="wwwroot\img\flags\ee.png" />
    <None Include="wwwroot\img\flags\eg.png" />
    <None Include="wwwroot\img\flags\eh.png" />
    <None Include="wwwroot\img\flags\england.png" />
    <None Include="wwwroot\img\flags\er.png" />
    <None Include="wwwroot\img\flags\es.png" />
    <None Include="wwwroot\img\flags\et.png" />
    <None Include="wwwroot\img\flags\europeanunion.png" />
    <None Include="wwwroot\img\flags\fam.png" />
    <None Include="wwwroot\img\flags\fi.png" />
    <None Include="wwwroot\img\flags\fj.png" />
    <None Include="wwwroot\img\flags\fk.png" />
    <None Include="wwwroot\img\flags\fm.png" />
    <None Include="wwwroot\img\flags\fo.png" />
    <None Include="wwwroot\img\flags\fr.png" />
    <None Include="wwwroot\img\flags\ga.png" />
    <None Include="wwwroot\img\flags\gb.png" />
    <None Include="wwwroot\img\flags\gd.png" />
    <None Include="wwwroot\img\flags\ge.png" />
    <None Include="wwwroot\img\flags\gf.png" />
    <None Include="wwwroot\img\flags\gh.png" />
    <None Include="wwwroot\img\flags\gi.png" />
    <None Include="wwwroot\img\flags\gl.png" />
    <None Include="wwwroot\img\flags\gm.png" />
    <None Include="wwwroot\img\flags\gn.png" />
    <None Include="wwwroot\img\flags\gp.png" />
    <None Include="wwwroot\img\flags\gq.png" />
    <None Include="wwwroot\img\flags\gr.png" />
    <None Include="wwwroot\img\flags\gs.png" />
    <None Include="wwwroot\img\flags\gt.png" />
    <None Include="wwwroot\img\flags\gu.png" />
    <None Include="wwwroot\img\flags\gw.png" />
    <None Include="wwwroot\img\flags\gy.png" />
    <None Include="wwwroot\img\flags\hk.png" />
    <None Include="wwwroot\img\flags\hm.png" />
    <None Include="wwwroot\img\flags\hn.png" />
    <None Include="wwwroot\img\flags\hr.png" />
    <None Include="wwwroot\img\flags\ht.png" />
    <None Include="wwwroot\img\flags\hu.png" />
    <None Include="wwwroot\img\flags\id.png" />
    <None Include="wwwroot\img\flags\ie.png" />
    <None Include="wwwroot\img\flags\il.png" />
    <None Include="wwwroot\img\flags\in.png" />
    <None Include="wwwroot\img\flags\io.png" />
    <None Include="wwwroot\img\flags\iq.png" />
    <None Include="wwwroot\img\flags\ir.png" />
    <None Include="wwwroot\img\flags\is.png" />
    <None Include="wwwroot\img\flags\it.png" />
    <None Include="wwwroot\img\flags\jm.png" />
    <None Include="wwwroot\img\flags\jo.png" />
    <None Include="wwwroot\img\flags\jp.png" />
    <None Include="wwwroot\img\flags\ke.png" />
    <None Include="wwwroot\img\flags\kg.png" />
    <None Include="wwwroot\img\flags\kh.png" />
    <None Include="wwwroot\img\flags\ki.png" />
    <None Include="wwwroot\img\flags\km.png" />
    <None Include="wwwroot\img\flags\kn.png" />
    <None Include="wwwroot\img\flags\kp.png" />
    <None Include="wwwroot\img\flags\kr.png" />
    <None Include="wwwroot\img\flags\kw.png" />
    <None Include="wwwroot\img\flags\ky.png" />
    <None Include="wwwroot\img\flags\kz.png" />
    <None Include="wwwroot\img\flags\la.png" />
    <None Include="wwwroot\img\flags\lb.png" />
    <None Include="wwwroot\img\flags\lc.png" />
    <None Include="wwwroot\img\flags\li.png" />
    <None Include="wwwroot\img\flags\lk.png" />
    <None Include="wwwroot\img\flags\lr.png" />
    <None Include="wwwroot\img\flags\ls.png" />
    <None Include="wwwroot\img\flags\lt.png" />
    <None Include="wwwroot\img\flags\lu.png" />
    <None Include="wwwroot\img\flags\lv.png" />
    <None Include="wwwroot\img\flags\ly.png" />
    <None Include="wwwroot\img\flags\ma.png" />
    <None Include="wwwroot\img\flags\mc.png" />
    <None Include="wwwroot\img\flags\md.png" />
    <None Include="wwwroot\img\flags\me.png" />
    <None Include="wwwroot\img\flags\mg.png" />
    <None Include="wwwroot\img\flags\mh.png" />
    <None Include="wwwroot\img\flags\mk.png" />
    <None Include="wwwroot\img\flags\ml.png" />
    <None Include="wwwroot\img\flags\mm.png" />
    <None Include="wwwroot\img\flags\mn.png" />
    <None Include="wwwroot\img\flags\mo.png" />
    <None Include="wwwroot\img\flags\mp.png" />
    <None Include="wwwroot\img\flags\mq.png" />
    <None Include="wwwroot\img\flags\mr.png" />
    <None Include="wwwroot\img\flags\ms.png" />
    <None Include="wwwroot\img\flags\mt.png" />
    <None Include="wwwroot\img\flags\mu.png" />
    <None Include="wwwroot\img\flags\mv.png" />
    <None Include="wwwroot\img\flags\mw.png" />
    <None Include="wwwroot\img\flags\mx.png" />
    <None Include="wwwroot\img\flags\my.png" />
    <None Include="wwwroot\img\flags\mz.png" />
    <None Include="wwwroot\img\flags\na.png" />
    <None Include="wwwroot\img\flags\nc.png" />
    <None Include="wwwroot\img\flags\ne.png" />
    <None Include="wwwroot\img\flags\nf.png" />
    <None Include="wwwroot\img\flags\ng.png" />
    <None Include="wwwroot\img\flags\ni.png" />
    <None Include="wwwroot\img\flags\nl.png" />
    <None Include="wwwroot\img\flags\no.png" />
    <None Include="wwwroot\img\flags\np.png" />
    <None Include="wwwroot\img\flags\nr.png" />
    <None Include="wwwroot\img\flags\nu.png" />
    <None Include="wwwroot\img\flags\nz.png" />
    <None Include="wwwroot\img\flags\om.png" />
    <None Include="wwwroot\img\flags\pa.png" />
    <None Include="wwwroot\img\flags\pe.png" />
    <None Include="wwwroot\img\flags\pf.png" />
    <None Include="wwwroot\img\flags\pg.png" />
    <None Include="wwwroot\img\flags\ph.png" />
    <None Include="wwwroot\img\flags\pk.png" />
    <None Include="wwwroot\img\flags\pl.png" />
    <None Include="wwwroot\img\flags\pm.png" />
    <None Include="wwwroot\img\flags\pn.png" />
    <None Include="wwwroot\img\flags\pr.png" />
    <None Include="wwwroot\img\flags\ps.png" />
    <None Include="wwwroot\img\flags\pt.png" />
    <None Include="wwwroot\img\flags\pw.png" />
    <None Include="wwwroot\img\flags\py.png" />
    <None Include="wwwroot\img\flags\qa.png" />
    <None Include="wwwroot\img\flags\re.png" />
    <None Include="wwwroot\img\flags\readme.txt" />
    <None Include="wwwroot\img\flags\ro.png" />
    <None Include="wwwroot\img\flags\rs.png" />
    <None Include="wwwroot\img\flags\ru.png" />
    <None Include="wwwroot\img\flags\rw.png" />
    <None Include="wwwroot\img\flags\sa.png" />
    <None Include="wwwroot\img\flags\sb.png" />
    <None Include="wwwroot\img\flags\sc.png" />
    <None Include="wwwroot\img\flags\scotland.png" />
    <None Include="wwwroot\img\flags\sd.png" />
    <None Include="wwwroot\img\flags\se.png" />
    <None Include="wwwroot\img\flags\sg.png" />
    <None Include="wwwroot\img\flags\sh.png" />
    <None Include="wwwroot\img\flags\si.png" />
    <None Include="wwwroot\img\flags\sj.png" />
    <None Include="wwwroot\img\flags\sk.png" />
    <None Include="wwwroot\img\flags\sl.png" />
    <None Include="wwwroot\img\flags\sm.png" />
    <None Include="wwwroot\img\flags\sn.png" />
    <None Include="wwwroot\img\flags\so.png" />
    <None Include="wwwroot\img\flags\sr.png" />
    <None Include="wwwroot\img\flags\st.png" />
    <None Include="wwwroot\img\flags\sv.png" />
    <None Include="wwwroot\img\flags\sy.png" />
    <None Include="wwwroot\img\flags\sz.png" />
    <None Include="wwwroot\img\flags\tc.png" />
    <None Include="wwwroot\img\flags\td.png" />
    <None Include="wwwroot\img\flags\tf.png" />
    <None Include="wwwroot\img\flags\tg.png" />
    <None Include="wwwroot\img\flags\th.png" />
    <None Include="wwwroot\img\flags\tj.png" />
    <None Include="wwwroot\img\flags\tk.png" />
    <None Include="wwwroot\img\flags\tl.png" />
    <None Include="wwwroot\img\flags\tm.png" />
    <None Include="wwwroot\img\flags\tn.png" />
    <None Include="wwwroot\img\flags\to.png" />
    <None Include="wwwroot\img\flags\tr.png" />
    <None Include="wwwroot\img\flags\tt.png" />
    <None Include="wwwroot\img\flags\tv.png" />
    <None Include="wwwroot\img\flags\tw.png" />
    <None Include="wwwroot\img\flags\tz.png" />
    <None Include="wwwroot\img\flags\ua.png" />
    <None Include="wwwroot\img\flags\ug.png" />
    <None Include="wwwroot\img\flags\um.png" />
    <None Include="wwwroot\img\flags\us.png" />
    <None Include="wwwroot\img\flags\uy.png" />
    <None Include="wwwroot\img\flags\uz.png" />
    <None Include="wwwroot\img\flags\va.png" />
    <None Include="wwwroot\img\flags\vc.png" />
    <None Include="wwwroot\img\flags\ve.png" />
    <None Include="wwwroot\img\flags\vg.png" />
    <None Include="wwwroot\img\flags\vi.png" />
    <None Include="wwwroot\img\flags\vn.png" />
    <None Include="wwwroot\img\flags\vu.png" />
    <None Include="wwwroot\img\flags\wales.png" />
    <None Include="wwwroot\img\flags\wf.png" />
    <None Include="wwwroot\img\flags\ws.png" />
    <None Include="wwwroot\img\flags\ye.png" />
    <None Include="wwwroot\img\flags\yt.png" />
    <None Include="wwwroot\img\flags\za.png" />
    <None Include="wwwroot\img\flags\zm.png" />
    <None Include="wwwroot\img\flags\zw.png" />
    <None Include="wwwroot\img\img-shadow.png" />
    <None Include="wwwroot\img\jm_denis.jpg" />
    <None Include="wwwroot\img\kaiadmin\demo1.png" />
    <None Include="wwwroot\img\kaiadmin\demo2.png" />
    <None Include="wwwroot\img\kaiadmin\demo3.png" />
    <None Include="wwwroot\img\kaiadmin\demo4.png" />
    <None Include="wwwroot\img\kaiadmin\demo5.png" />
    <None Include="wwwroot\img\kaiadmin\demo6.png" />
    <None Include="wwwroot\img\kaiadmin\demo7.png" />
    <None Include="wwwroot\img\kaiadmin\demo8.png" />
    <None Include="wwwroot\img\kaiadmin\demo9.png" />
    <None Include="wwwroot\img\kaiadmin\favicon.ico" />
    <None Include="wwwroot\img\kaiadmin\favicon.png" />
    <None Include="wwwroot\img\kaiadmin\favicon.svg" />
    <None Include="wwwroot\img\kaiadmin\icon.png" />
    <None Include="wwwroot\img\kaiadmin\icon.svg" />
    <None Include="wwwroot\img\kaiadmin\logo_dark.png" />
    <None Include="wwwroot\img\kaiadmin\logo_dark.svg" />
    <None Include="wwwroot\img\kaiadmin\logo_documentation.png" />
    <None Include="wwwroot\img\kaiadmin\logo_light.png" />
    <None Include="wwwroot\img\kaiadmin\logo_light.svg" />
    <None Include="wwwroot\img\logoproduct.svg" />
    <None Include="wwwroot\img\logoproduct2.svg" />
    <None Include="wwwroot\img\logoproduct3.svg" />
    <None Include="wwwroot\img\mlane.jpg" />
    <None Include="wwwroot\img\profile.jpg" />
    <None Include="wwwroot\img\profile2.jpg" />
    <None Include="wwwroot\img\sauro.jpg" />
    <None Include="wwwroot\img\talha.jpg" />
    <None Include="wwwroot\img\undraw\undraw_blank_canvas_3rbb.svg" />
    <None Include="wwwroot\img\undraw\undraw_creative_team_r90h.svg" />
    <None Include="wwwroot\img\undraw\undraw_empty_xct9.svg" />
    <None Include="wwwroot\img\undraw\undraw_Hello_qnas.svg" />
    <None Include="wwwroot\img\undraw\undraw_not_found_60pq.svg" />
    <None Include="wwwroot\img\undraw\undraw_no_data_qbuo.svg" />
    <None Include="wwwroot\img\undraw\undraw_page_not_found_su7k.svg" />
    <None Include="wwwroot\img\undraw\undraw_sign_in_e6hj.svg" />
    <None Include="wwwroot\img\undraw\undraw_tabs_jf82.svg" />
    <None Include="wwwroot\img\undraw\undraw_Taken_if77.svg" />
    <None Include="wwwroot\img\undraw\undraw_update_uxn2.svg" />
    <None Include="wwwroot\img\undraw\undraw_upgrade_06a0.svg" />
    <None Include="wwwroot\img\visa.svg" />
    <None Include="wwwroot\js\core\bootstrap.min.js" />
    <None Include="wwwroot\js\core\jquery-3.7.1.min.js" />
    <None Include="wwwroot\js\core\popper.min.js" />
    <None Include="wwwroot\js\demo.js" />
    <None Include="wwwroot\js\kaiadmin.js" />
    <None Include="wwwroot\js\plugin\bootstrap-notify\bootstrap-notify.min.js" />
    <None Include="wwwroot\js\plugin\bootstrap-tagsinput\bootstrap-tagsinput.min.js" />
    <None Include="wwwroot\js\plugin\bootstrap-toggle\bootstrap-toggle.min.js" />
    <None Include="wwwroot\js\plugin\chart-circle\circles.min.js" />
    <None Include="wwwroot\js\plugin\chart.js\chart.min.js" />
    <None Include="wwwroot\js\plugin\datatables\datatables.min.js" />
    <None Include="wwwroot\js\plugin\datepicker\bootstrap-datetimepicker.min.js" />
    <None Include="wwwroot\js\plugin\dropzone\dropzone.min.js" />
    <None Include="wwwroot\js\plugin\fullcalendar\fullcalendar.min.js" />
    <None Include="wwwroot\js\plugin\gmaps\gmaps.js" />
    <None Include="wwwroot\js\plugin\jquery-scrollbar\jquery.scrollbar.min.js" />
    <None Include="wwwroot\js\plugin\jquery.magnific-popup\jquery.magnific-popup.min.js" />
    <None Include="wwwroot\js\plugin\jquery.sparkline\jquery.sparkline.min.js" />
    <None Include="wwwroot\js\plugin\jquery.validate\jquery.validate.min.js" />
    <None Include="wwwroot\js\plugin\jsvectormap\jsvectormap.min.js" />
    <None Include="wwwroot\js\plugin\jsvectormap\world.js" />
    <None Include="wwwroot\js\plugin\list.js\list.min.js" />
    <None Include="wwwroot\js\plugin\moment\moment.min.js" />
    <None Include="wwwroot\js\plugin\owl-carousel\ajax-loader.gif" />
    <None Include="wwwroot\js\plugin\owl-carousel\owl.carousel.min.js" />
    <None Include="wwwroot\js\plugin\owl-carousel\owl.video.play.png" />
    <None Include="wwwroot\js\plugin\select2\select2.full.min.js" />
    <None Include="wwwroot\js\plugin\sortable\sortable.min.js" />
    <None Include="wwwroot\js\plugin\sticky-sidebar\sticky-sidebar.min.js" />
    <None Include="wwwroot\js\plugin\summernote\summernote-lite.min.js" />
    <None Include="wwwroot\js\plugin\sweetalert\sweetalert.min.js" />
    <None Include="wwwroot\js\plugin\webfont\webfont.min.js" />
    <None Include="wwwroot\js\setting-demo.js" />
    <None Include="wwwroot\js\setting-demo2.js" />
  </ItemGroup>

</Project>
